### ISSUE TITLE
Language es-ES for the Joomlage Router

### ISSUE THREAD

**Issue by Los-Carnales** [Hackwar/jlrouter#4]
Dear Hannes aka @Hackwar , i have translated into Spanish the two lenguage files of the Joomlage Router. This may be for users who do not speak or understand English well.

[es-ES.zip](https://github.com/Hackwar/jlrouter/files/919184/es-ES.zip)

I am testing your router on localhost with several projects that I have to do once I get out Joomla 3.7 or 3.8. Next I will write another post about the possible errors that I find in his great work.

**Comment by Hackwar** [comment]
I've added your translation files to the repository. I will provide a new release soon with this and a few other small improvements. Thank you very much for your contribution!

**Comment by Los-Carnales** [comment]
@Hackwar Thanks to you for what you are doing for the Joomla community. When you take out the new version I will look at whether to translate more text.
